version: '3'

services:
  app:
    build: .
    volumes:
      - ./site:/var/www/html
    ports:
      - "${PORT}:80"
    restart: unless-stopped
  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: xe
      MYSQL_DATABASE: xe